package main

import "encoding/xml"

type Module struct {
	XMLName    xml.Name `xml:"Module"`
	Text       string   `xml:",chardata"`
	Version    string   `xml:"version,attr"`
	Xmlns      string   `xml:"xmlns,attr"`
	FormModule struct {
		Text           string `xml:",chardata"`
		Name           string `xml:"Name,attr"`
		DirtyInfo      string `xml:"DirtyInfo,attr"`
		Title          string `xml:"Title,attr"`
		Comment        string `xml:"Comment,attr"`
		NewdeferReqEnf string `xml:"NewdeferReqEnf,attr"`
		MenuModule     string `xml:"MenuModule,attr"`
		ConsoleWindow  string `xml:"ConsoleWindow,attr"`
		Coordinate     struct {
			Text                string `xml:",chardata"`
			CharacterCellWidth  string `xml:"CharacterCellWidth,attr"`
			DefaultFontScaling  string `xml:"DefaultFontScaling,attr"`
			CoordinateSystem    string `xml:"CoordinateSystem,attr"`
			CharacterCellHeight string `xml:"CharacterCellHeight,attr"`
			RealUnit            string `xml:"RealUnit,attr"`
		} `xml:"Coordinate"`
		Alert []struct {
			Text                string `xml:",chardata"`
			Name                string `xml:"Name,attr"`
			Button2Label        string `xml:"Button2Label,attr"`
			AlertStyle          string `xml:"AlertStyle,attr"`
			Button1Label        string `xml:"Button1Label,attr"`
			DefaultAlertButton  string `xml:"DefaultAlertButton,attr"`
			Button3Label        string `xml:"Button3Label,attr"`
			SubclassObjectGroup string `xml:"SubclassObjectGroup,attr"`
			DirtyInfo           string `xml:"DirtyInfo,attr"`
			Title               string `xml:"Title,attr"`
			AlertMessage        string `xml:"AlertMessage,attr"`
			LanguageDirection   string `xml:"LanguageDirection,attr"`
		} `xml:"Alert"`
		Block []struct {
			Text                 string `xml:",chardata"`
			Name                 string `xml:"Name,attr"`
			DirtyInfo            string `xml:"DirtyInfo,attr"`
			WhereClause          string `xml:"WhereClause,attr"`
			ScrollbarWidth       string `xml:"ScrollbarWidth,attr"`
			QueryDataSourceName  string `xml:"QueryDataSourceName,attr"`
			ParentType           string `xml:"ParentType,attr"`
			ParentFilename       string `xml:"ParentFilename,attr"`
			OrderByClause        string `xml:"OrderByClause,attr"`
			ScrollbarLength      string `xml:"ScrollbarLength,attr"`
			ParentModule         string `xml:"ParentModule,attr"`
			ParentModuleType     string `xml:"ParentModuleType,attr"`
			ParentName           string `xml:"ParentName,attr"`
			UpdateAllowed        string `xml:"UpdateAllowed,attr"`
			ScrollbarTabPageName string `xml:"ScrollbarTabPageName,attr"`
			RecordsFetchedCount  string `xml:"RecordsFetchedCount,attr"`
			RecordsDisplayCount  string `xml:"RecordsDisplayCount,attr"`
			InsertAllowed        string `xml:"InsertAllowed,attr"`
			RecordsBufferedCount string `xml:"RecordsBufferedCount,attr"`
			ScrollbarYPosition   string `xml:"ScrollbarYPosition,attr"`
			ScrollbarCanvasName  string `xml:"ScrollbarCanvasName,attr"`
			ScrollbarXPosition   string `xml:"ScrollbarXPosition,attr"`
			DatabaseBlock        bool   `xml:"DatabaseBlock,attr"`
			SubclassObjectGroup  string `xml:"SubclassObjectGroup,attr"`
			Item                 []struct {
				Text                           string `xml:",chardata"`
				Name                           string `xml:"Name,attr"`
				DirtyInfo                      string `xml:"DirtyInfo,attr"`
				DatabaseItem                   string `xml:"DatabaseItem,attr"`
				Width                          string `xml:"Width,attr"`
				Height                         string `xml:"Height,attr"`
				Comment                        string `xml:"Comment,attr"`
				MaximumLength                  string `xml:"MaximumLength,attr"`
				YPosition                      string `xml:"YPosition,attr"`
				XPosition                      string `xml:"XPosition,attr"`
				ParentFilename                 string `xml:"ParentFilename,attr"`
				ItemsDisplay                   string `xml:"ItemsDisplay,attr"`
				DistanceBetweenRecords         string `xml:"DistanceBetweenRecords,attr"`
				ParentModule                   string `xml:"ParentModule,attr"`
				ParentModuleType               string `xml:"ParentModuleType,attr"`
				ParentName                     string `xml:"ParentName,attr"`
				Prompt                         string `xml:"Prompt,attr"`
				TabPageName                    string `xml:"TabPageName,attr"`
				PromptDisplayStyle             string `xml:"PromptDisplayStyle,attr"`
				PromptAttachmentOffset         string `xml:"PromptAttachmentOffset,attr"`
				ColumnName                     string `xml:"ColumnName,attr"`
				ParentType                     string `xml:"ParentType,attr"`
				CanvasName                     string `xml:"CanvasName,attr"`
				PopupMenuName                  string `xml:"PopupMenuName,attr"`
				CaseRestriction                string `xml:"CaseRestriction,attr"`
				Required                       string `xml:"Required,attr"`
				UpdateAllowed                  string `xml:"UpdateAllowed,attr"`
				ValidateFromList               string `xml:"ValidateFromList,attr"`
				LovName                        string `xml:"LovName,attr"`
				WrapStyle                      string `xml:"WrapStyle,attr"`
				PromptFontSize                 string `xml:"PromptFontSize,attr"`
				PromptFontSpacing              string `xml:"PromptFontSpacing,attr"`
				PromptFontWeight               string `xml:"PromptFontWeight,attr"`
				PromptFontStyle                string `xml:"PromptFontStyle,attr"`
				PromptFontName                 string `xml:"PromptFontName,attr"`
				FormatMask                     string `xml:"FormatMask,attr"`
				DataType                       string `xml:"DataType,attr"`
				PromptJustification            string `xml:"PromptJustification,attr"`
				PromptAttachmentEdge           string `xml:"PromptAttachmentEdge,attr"`
				PromptAlign                    string `xml:"PromptAlign,attr"`
				PromptAlignOffset              string `xml:"PromptAlignOffset,attr"`
				MultiLine                      string `xml:"MultiLine,attr"`
				UncheckedValue                 string `xml:"UncheckedValue,attr"`
				CheckedValue                   string `xml:"CheckedValue,attr"`
				CheckBoxOtherValues            string `xml:"CheckBoxOtherValues,attr"`
				ItemType                       string `xml:"ItemType,attr"`
				InitializeValue                string `xml:"InitializeValue,attr"`
				Justification                  string `xml:"Justification,attr"`
				ListElementCount               string `xml:"ListElementCount,attr"`
				KeyboardNavigable              string `xml:"KeyboardNavigable,attr"`
				InsertAllowed                  string `xml:"InsertAllowed,attr"`
				CopyValueFromItem              string `xml:"CopyValueFromItem,attr"`
				Label                          string `xml:"Label,attr"`
				RecordVisualAttributeGroupName string `xml:"RecordVisualAttributeGroupName,attr"`
				BackColor                      string `xml:"BackColor,attr"`
				FontWeight                     string `xml:"FontWeight,attr"`
				ForegroundColor                string `xml:"ForegroundColor,attr"`
				FontSize                       string `xml:"FontSize,attr"`
				FontName                       string `xml:"FontName,attr"`
				MouseNavigate                  string `xml:"MouseNavigate,attr"`
				FontStyle                      string `xml:"FontStyle,attr"`
				FontSpacing                    string `xml:"FontSpacing,attr"`
				SubclassSubObject              string `xml:"SubclassSubObject,attr"`
				Trigger                        []struct {
					Text              string `xml:",chardata"`
					Name              string `xml:"Name,attr"`
					TriggerText       string `xml:"TriggerText,attr"`
					DirtyInfo         string `xml:"DirtyInfo,attr"`
					SubclassSubObject string `xml:"SubclassSubObject,attr"`
				} `xml:"Trigger"`
				RadioButton []struct {
					Text              string `xml:",chardata"`
					Name              string `xml:"Name,attr"`
					SubclassSubObject string `xml:"SubclassSubObject,attr"`
					DirtyInfo         string `xml:"DirtyInfo,attr"`
				} `xml:"RadioButton"`
			} `xml:"Item"`
			DataSourceColumn []struct {
				Text          string `xml:",chardata"`
				Type          string `xml:"Type,attr"`
				DSCType       string `xml:"DSCType,attr"`
				DSCName       string `xml:"DSCName,attr"`
				DSCNochildren string `xml:"DSCNochildren,attr"`
				DSCLength     string `xml:"DSCLength,attr"`
				DSCMandatory  string `xml:"DSCMandatory,attr"`
				DSCPrecision  string `xml:"DSCPrecision,attr"`
				DSCScale      string `xml:"DSCScale,attr"`
			} `xml:"DataSourceColumn"`
			Relation struct {
				Text                        string `xml:",chardata"`
				Name                        string `xml:"Name,attr"`
				DeleteRecord                string `xml:"DeleteRecord,attr"`
				Deferred                    string `xml:"Deferred,attr"`
				DirtyInfo                   string `xml:"DirtyInfo,attr"`
				JoinCondition               string `xml:"JoinCondition,attr"`
				DetailBlock                 string `xml:"DetailBlock,attr"`
				RelationType                string `xml:"RelationType,attr"`
				AutoQuery                   string `xml:"AutoQuery,attr"`
				PreventMasterlessOperations string `xml:"PreventMasterlessOperations,attr"`
			} `xml:"Relation"`
			Trigger []struct {
				Text              string `xml:",chardata"`
				Name              string `xml:"Name,attr"`
				TriggerText       string `xml:"TriggerText,attr"`
				DirtyInfo         string `xml:"DirtyInfo,attr"`
				SubclassSubObject string `xml:"SubclassSubObject,attr"`
			} `xml:"Trigger"`
		} `xml:"Block"`
		Canvas []struct {
			Text                      string `xml:",chardata"`
			Name                      string `xml:"Name,attr"`
			ParentFilename            string `xml:"ParentFilename,attr"`
			ParentModule              string `xml:"ParentModule,attr"`
			ParentModuleType          string `xml:"ParentModuleType,attr"`
			ParentName                string `xml:"ParentName,attr"`
			ViewportXPositionOnCanvas string `xml:"ViewportXPositionOnCanvas,attr"`
			ViewportYPositionOnCanvas string `xml:"ViewportYPositionOnCanvas,attr"`
			DirtyInfo                 string `xml:"DirtyInfo,attr"`
			Width                     string `xml:"Width,attr"`
			RaiseOnEnter              string `xml:"RaiseOnEnter,attr"`
			ParentType                string `xml:"ParentType,attr"`
			PopupMenuName             string `xml:"PopupMenuName,attr"`
			Height                    string `xml:"Height,attr"`
			ViewportHeight            string `xml:"ViewportHeight,attr"`
			ViewportWidth             string `xml:"ViewportWidth,attr"`
			CanvasType                string `xml:"CanvasType,attr"`
			ShowHorizontalScrollbar   string `xml:"ShowHorizontalScrollbar,attr"`
			ViewportYPosition         string `xml:"ViewportYPosition,attr"`
			ViewportXPosition         string `xml:"ViewportXPosition,attr"`
			WindowName                string `xml:"WindowName,attr"`
			DisplayViewport           string `xml:"DisplayViewport,attr"`
			SubclassObjectGroup       string `xml:"SubclassObjectGroup,attr"`
			Bevel                     string `xml:"Bevel,attr"`
			Graphics                  []struct {
				Text                   string `xml:",chardata"`
				Name                   string `xml:"Name,attr"`
				YPosition              string `xml:"YPosition,attr"`
				XPosition              string `xml:"XPosition,attr"`
				GraphicsType           string `xml:"GraphicsType,attr"`
				FillPattern            string `xml:"FillPattern,attr"`
				Bevel                  string `xml:"Bevel,attr"`
				DirtyInfo              string `xml:"DirtyInfo,attr"`
				UpdateLayout           string `xml:"UpdateLayout,attr"`
				Width                  string `xml:"Width,attr"`
				ScrollbarWidth         string `xml:"ScrollbarWidth,attr"`
				Height                 string `xml:"Height,attr"`
				EdgePattern            string `xml:"EdgePattern,attr"`
				GraphicsFontColorCode  string `xml:"GraphicsFontColorCode,attr"`
				GraphicsFontColor      string `xml:"GraphicsFontColor,attr"`
				EdgeBackColor          string `xml:"EdgeBackColor,attr"`
				FrameTitleOffset       string `xml:"FrameTitleOffset,attr"`
				FrameTitleSpacing      string `xml:"FrameTitleSpacing,attr"`
				VerticalMargin         string `xml:"VerticalMargin,attr"`
				HorizontalMargin       string `xml:"HorizontalMargin,attr"`
				GraphicsText           string `xml:"GraphicsText,attr"`
				HorizontalObjectOffset string `xml:"HorizontalObjectOffset,attr"`
				LayoutDataBlockName    string `xml:"LayoutDataBlockName,attr"`
				StartPromptOffset      string `xml:"StartPromptOffset,attr"`
				GraphicsFontName       string `xml:"GraphicsFontName,attr"`
				GraphicsFontStyle      string `xml:"GraphicsFontStyle,attr"`
				GraphicsFontWeight     string `xml:"GraphicsFontWeight,attr"`
				GraphicsFontSize       string `xml:"GraphicsFontSize,attr"`
				GraphicsFontSpacing    string `xml:"GraphicsFontSpacing,attr"`
				RecordsDisplayCount    string `xml:"RecordsDisplayCount,attr"`
				ShowScrollbar          string `xml:"ShowScrollbar,attr"`
				LayoutStyle            string `xml:"LayoutStyle,attr"`
				JoinStyle              string `xml:"JoinStyle,attr"`
				SubclassSubObject      string `xml:"SubclassSubObject,attr"`
			} `xml:"Graphics"`
		} `xml:"Canvas"`
		ModuleParameter []struct {
			Text                string `xml:",chardata"`
			Name                string `xml:"Name,attr"`
			DirtyInfo           string `xml:"DirtyInfo,attr"`
			ParameterDataType   string `xml:"ParameterDataType,attr"`
			SubclassObjectGroup string `xml:"SubclassObjectGroup,attr"`
			Comment             string `xml:"Comment,attr"`
		} `xml:"ModuleParameter"`
		LOV []struct {
			Text                string `xml:",chardata"`
			Name                string `xml:"Name,attr"`
			DirtyInfo           string `xml:"DirtyInfo,attr"`
			RecordGroupName     string `xml:"RecordGroupName,attr"`
			ParentType          string `xml:"ParentType,attr"`
			ParentFilename      string `xml:"ParentFilename,attr"`
			Title               string `xml:"Title,attr"`
			FilterBeforeDisplay string `xml:"FilterBeforeDisplay,attr"`
			ParentModule        string `xml:"ParentModule,attr"`
			ParentModuleType    string `xml:"ParentModuleType,attr"`
			ParentName          string `xml:"ParentName,attr"`
			LOVColumnMapping    []struct {
				Text         string `xml:",chardata"`
				Name         string `xml:"Name,attr"`
				DirtyInfo    string `xml:"DirtyInfo,attr"`
				Title        string `xml:"Title,attr"`
				DisplayWidth string `xml:"DisplayWidth,attr"`
				ReturnItem   string `xml:"ReturnItem,attr"`
			} `xml:"LOVColumnMapping"`
		} `xml:"LOV"`
		Menu []struct {
			Text                string `xml:",chardata"`
			Name                string `xml:"Name,attr"`
			DirtyInfo           string `xml:"DirtyInfo,attr"`
			ParentType          string `xml:"ParentType,attr"`
			ParentFilename      string `xml:"ParentFilename,attr"`
			ParentModule        string `xml:"ParentModule,attr"`
			ParentModuleType    string `xml:"ParentModuleType,attr"`
			ParentName          string `xml:"ParentName,attr"`
			SubclassObjectGroup string `xml:"SubclassObjectGroup,attr"`
			MenuItem            []struct {
				Text              string `xml:",chardata"`
				Name              string `xml:"Name,attr"`
				SubclassSubObject string `xml:"SubclassSubObject,attr"`
				DirtyInfo         string `xml:"DirtyInfo,attr"`
			} `xml:"MenuItem"`
		} `xml:"Menu"`
		ProgramUnit []struct {
			Text                string `xml:",chardata"`
			Name                string `xml:"Name,attr"`
			ProgramUnitType     string `xml:"ProgramUnitType,attr"`
			ParentType          string `xml:"ParentType,attr"`
			ParentFilename      string `xml:"ParentFilename,attr"`
			ParentModule        string `xml:"ParentModule,attr"`
			ParentModuleType    string `xml:"ParentModuleType,attr"`
			ParentName          string `xml:"ParentName,attr"`
			ProgramUnitText     string `xml:"ProgramUnitText,attr"`
			SubclassObjectGroup string `xml:"SubclassObjectGroup,attr"`
		} `xml:"ProgramUnit"`
		RecordGroup []struct {
			Text              string `xml:",chardata"`
			Name              string `xml:"Name,attr"`
			DirtyInfo         string `xml:"DirtyInfo,attr"`
			RecordGroupType   string `xml:"RecordGroupType,attr"`
			RecordGroupQuery  string `xml:"RecordGroupQuery,attr"`
			RecordGroupColumn []struct {
				Text           string `xml:",chardata"`
				Name           string `xml:"Name,attr"`
				MaximumLength  string `xml:"MaximumLength,attr"`
				DirtyInfo      string `xml:"DirtyInfo,attr"`
				ColumnDataType string `xml:"ColumnDataType,attr"`
			} `xml:"RecordGroupColumn"`
		} `xml:"RecordGroup"`
		Report struct {
			Text             string `xml:",chardata"`
			Name             string `xml:"Name,attr"`
			DirtyInfo        string `xml:"DirtyInfo,attr"`
			ParentType       string `xml:"ParentType,attr"`
			ParentFilename   string `xml:"ParentFilename,attr"`
			ParentModule     string `xml:"ParentModule,attr"`
			ParentModuleType string `xml:"ParentModuleType,attr"`
			ParentName       string `xml:"ParentName,attr"`
		} `xml:"Report"`
		Trigger []struct {
			Text                string `xml:",chardata"`
			Name                string `xml:"Name,attr"`
			SubclassObjectGroup string `xml:"SubclassObjectGroup,attr"`
			TriggerText         string `xml:"TriggerText,attr"`
			DirtyInfo           string `xml:"DirtyInfo,attr"`
			ParentType          string `xml:"ParentType,attr"`
			ParentFilename      string `xml:"ParentFilename,attr"`
			ParentModule        string `xml:"ParentModule,attr"`
			ParentModuleType    string `xml:"ParentModuleType,attr"`
			ParentName          string `xml:"ParentName,attr"`
		} `xml:"Trigger"`
		VisualAttribute []struct {
			Text                string `xml:",chardata"`
			Name                string `xml:"Name,attr"`
			SubclassObjectGroup string `xml:"SubclassObjectGroup,attr"`
			DirtyInfo           string `xml:"DirtyInfo,attr"`
			ParentType          string `xml:"ParentType,attr"`
			ParentFilename      string `xml:"ParentFilename,attr"`
			ParentModule        string `xml:"ParentModule,attr"`
			ParentModuleType    string `xml:"ParentModuleType,attr"`
			ParentName          string `xml:"ParentName,attr"`
			FontWeight          string `xml:"FontWeight,attr"`
			BackColor           string `xml:"BackColor,attr"`
			ForegroundColor     string `xml:"ForegroundColor,attr"`
			FontName            string `xml:"FontName,attr"`
		} `xml:"VisualAttribute"`
		Window []struct {
			Text                string `xml:",chardata"`
			Name                string `xml:"Name,attr"`
			SubclassObjectGroup string `xml:"SubclassObjectGroup,attr"`
			DirtyInfo           string `xml:"DirtyInfo,attr"`
			Width               string `xml:"Width,attr"`
			ParentType          string `xml:"ParentType,attr"`
			ParentFilename      string `xml:"ParentFilename,attr"`
			Title               string `xml:"Title,attr"`
			Height              string `xml:"Height,attr"`
			ParentModule        string `xml:"ParentModule,attr"`
			ParentModuleType    string `xml:"ParentModuleType,attr"`
			ParentName          string `xml:"ParentName,attr"`
		} `xml:"Window"`
		ObjectGroup []struct {
			Text             string `xml:",chardata"`
			Name             string `xml:"Name,attr"`
			DirtyInfo        string `xml:"DirtyInfo,attr"`
			ParentType       string `xml:"ParentType,attr"`
			ParentFilename   string `xml:"ParentFilename,attr"`
			ParentModule     string `xml:"ParentModule,attr"`
			ParentModuleType string `xml:"ParentModuleType,attr"`
			ParentName       string `xml:"ParentName,attr"`
			ObjectGroupChild []struct {
				Text              string `xml:",chardata"`
				Name              string `xml:"Name,attr"`
				SubclassSubObject string `xml:"SubclassSubObject,attr"`
			} `xml:"ObjectGroupChild"`
		} `xml:"ObjectGroup"`
	} `xml:"FormModule"`
}
